#!/bin/bash
#rmg_process
#
# This script is part of the QRAAT system.
#
# Copyright (C) 2013 Christopher Patton
#
# This is a wrapper script for the processing .det files into the 
# database and archiving them. Eventually, we'll have additional 
# processing steps, such as filtering the est rows. In cron:
#	* * * * * rmg_process >>/var/log/rmg/rmg_process 2>&1
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Check for attempted reentry
name=`basename $0`
count=`pgrep -c $name`
if [ "$count" -gt "1" ]
then
	echo $name already running, bye!
	exit 1
fi

source rmg_env

echo Starting `date`
echo
echo det_to_db
rmg_det_to_db
#remove empty directories
find $RMG_SERVER_DET_DIR -mindepth 1 -depth -type d -empty -delete
echo 
echo position_auto
rmg_position_auto
#echo
#echo rmg_filterest
#rmg_filterest
echo
echo track_auto
rmg_track_auto
echo
echo Finished `date`
echo
