#!/bin/bash
#rmg_status
#
# This script is part of the QRAAT system.
#
# Copyright (C) 2013 Marcel Losekoot
#
# This script is responsible for updating the system side status information after setting the environment variables using rmg_env.
# Call this script from cron:
#	*/10 * * * * rmg_status
#
# It runs the following scripts:
#	rmg_readstatus, reads telemetry data from each of the sites
#	rmg_timecheck, reads clock offset from each of the sites 
#	rmg_detcount, counts the number of det files present at the site and at the server, for each site
#	rmg_plotstatus, generates the web plots.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Check for attempted reentry
name=`basename $0`
count=`pgrep -c $name`
if [ "$count" -gt "1" ]
then
        echo $name already running, `date`
        exit 1
fi

source rmg_env

echo Starting `date`
echo
echo Starting rmg_schedule `date`
echo rmg_schedule
rmg_schedule $RMG_SERVER_SITELIST $RMG_SERVER_TXLIST
echo Finished rmg_schedule `date`
echo
echo Starting rmg_readstatus `date`
echo rmg_readstatus
rmg_readstatus $RMG_SERVER_SITELIST $RMG_SERVER_METADATA_DIR/authfile
echo Finished rmg_readstatus `date`
echo
echo Starting rmg_timecheck `date`
echo rmg_timecheck
rmg_timecheck $RMG_SERVER_SITELIST $RMG_SERVER_METADATA_DIR/authfile
echo Finished rmg_timecheck `date`
echo
echo Starting rmg_detcount `date`
echo rmg_detcount
rmg_detcount $RMG_SERVER_SITELIST $RMG_SERVER_METADATA_DIR/authfile
echo Finished rmg_detcount `date`
echo
echo Starting rmg_estcount `date`
echo rmg_estcount
rmg_estcount $RMG_SERVER_SITELIST $RMG_SERVER_METADATA_DIR/authfile
echo Finished rmg_estcount `date`
echo
echo Starting rmg_dbstats `date`
echo rmg_dbstats
rmg_dbstats $RMG_SERVER_METADATA_DIR/authfile_readest
echo Finished rmg_dbstats `date`
echo
echo Starting rmg_plotstatus `date`
echo rmg_plotstatus
rmg_plotstatus $RMG_SERVER_SITELIST $RMG_SERVER_METADATA_DIR/authfile
echo Finished rmg_plotstatus `date`
echo
echo Finished `date`
echo
#END
