#!/bin/bash
#rmg_filterest
# This script is part of the QRAAT system.
#
# Copyright (C) 2013 Marcel Losekoot
#
# This script examines the est table and copies the 'good' rows to the fest table.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Check for attempted reentry
name=`basename $0`
count=`pgrep -c $name`
if [ "$count" -gt "1" ]
then
	echo $name already running, bye!
	exit 1
fi

echo
echo Starting `date`
# Set RMG environment variables
. rmg_env

# Get DB credentials
read user password name <<< $(rmg_csv --row view=writer user password name \
                                      < $RMG_SERVER_DIR/db_auth)

echo -n "Number of est entries to process: "
mysql -B --skip-column-names -e 'select count(id) from est where id > (select max(id) from fest);' $name
mysql --user=$user --password=$password \
      -B -e 'insert into fest select * from est where id > (select max(id) from fest) and band10 < 1000;' \
      $name

echo Finished `date`

#END
