#!/bin/bash
#rmg_zapflags
#
# This script is part of the QRAAT system.
#
# Copyright (C) 2013 Marcel Losekoot
#
# This script is responsible for deleting flag files upon reboot.
# Call this script from cron:
#	@reboot rmg_zapflags
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Dispense with the usual check for reentry

echo
echo Starting $0 at `date`
# Set RMG environment variables
source rmg_env

# Check that environment variables are actually set
echo Checking environment variables are set
if [ -z "$RMG_SERVER_DET_DIR" ]
then
	echo ERROR: environment variable RMG_SERVER_DET_DIR is not set, bailing out
	exit 1
fi

find $RMG_SERVER_DET_DIR -maxdepth 2 -type f -iname fetching.site -exec rm -f {} \;

#END
