#!/usr/bin/python

import rmg_position
import numpy as np
import os

cursor = rmg_position.get_db_cursor()

#get id of last processed record
cursor.execute("select last_processed from position_processing;")
last_processed = cursor.fetchone()[0]
print "Last EST record processed: {}".format(last_processed)

#get txs to-be-processed
cursor.execute("select distinct(txid) from est where ID > %s;", (last_processed,))
tx_list = cursor.fetchall()
print "{} transmitters found in new records".format(len(tx_list))

for tx in tx_list:
  txid = tx[0]
  print "Processing transmitter: {}".format(txid)
  #get times of to-be-processed records
  cursor.execute("select ID, timestamp from est where ID > %s and txid = %s order by timestamp ASC;", (last_processed,txid))
  times = np.array(cursor.fetchall(),dtype=float)

  print "Calculating time range"
  #determine time range needed to be processed
  #TODO source rmg_env
  time_window = os.environ['RMG_POS_TIME_WINDOW']
  time_ranges = []
  if times.shape[0] > 0:
    temp_range = [times[0,1] - time_window, times[0,1] + time_window]
    for j in range(1,times.shape[0]):
      if times[j,1] - time_window < temp_range[1]:
        temp_range[1] = times[j,1] + time_window
      else:
        time_ranges.append(temp_range)
        temp_range = [times[j,1] - time_window, times[j,1]]
  #TODO combine close ranges?

  time_delta = os.environ['RMG_POS_TIME_STEP']
  cal_id = os.environ['RMG_POS_CAL_ID']

  #process time ranges
  for time_range in time_ranges:
    print "Processing {0} - {1}".format(time_range)
    rmg_position.calc_positions(cal_id, txid, time_range[0], time_range[1], time_delta, time_window, cur = cursor)

#store id of last processed record
cursor.execute("update position_processing set last_processed=%s;", (np.max(times[0,:]),))
