#!/usr/bin/env python
#est_processing
#Processes the det files on the server into est files
#
# Copyright (C) 2013 Todd Borrowman, Christopher Patton
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from qraat import est_data

def process_det_files(det_dirname, est_dirname):
    print "Processing " + det_dirname
    est = est_data.est_data()
    est.read_dir(det_dirname)
    if est.num_tags > 0:
        #est.write_est(est_dirname)
        est.write_csv(est_dirname)

if __name__=="__main__":
    import sys, os
    if len(sys.argv) == 3:
        det_rmg_dir = sys.argv[1]
        if not os.path.exists(det_rmg_dir):
            raise ValueError('{0} .det file directory does not exist'.format(det_rmg_dir))
        if not det_rmg_dir[-1]=='/':
            det_rmg_dir += '/'
        est_rmg_dir = sys.argv[2]
        if not os.path.exists(est_rmg_dir):
            os.makedirs(est_rmg_dir)
        if not est_rmg_dir[-1]=='/':
            est_rmg_dir += '/'
        process_det_files(det_rmg_dir, est_rmg_dir)
    else:
        raise ValueError('Missing arguments! Use is \'est_processing site_det_directory site_est_directory\'')
