#!/bin/bash
# rmg_env
#
# This script is part of the QRAAT system. It provides system variables
# for running QRAAT.
#
# NB: Each variable must be defined using the export command.
#
# Copyright (C) 2013 Todd Borrowman
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Location of metadata on a remote machine. Files included in this
# directory are: site.csv, tx.csv, and status.log. Any debug information
# is also stored here. We currently log the standard output and standard
# error of the last run of the pulse detector. This value is used by the
# server and must be the same at each site.
export RMG_SITE_METADATA_DIR="/home/rmg"

# Location of det data files on a remote machine. This is typically a
# subdirectory of a temporary filesystem created with /etc/fstab.
# This value is used by the sever and must be the same at each site.
export RMG_SITE_DET_DIR="/tmp/ramdisk/det_files"

# The directory on the server where the server RMG files are stored.
# This convenience variable is local to this script.
export RMG_SERVER_DIR="/rmg_server"

# Location of metadata on the server. Files included in this directory
# are sitelist.csv and transmitter spec files.
export RMG_SERVER_METADATA_DIR="$RMG_SERVER_DIR"

# Location of archive on the server, used to store processed det and est files
# This vairable is used to identify the directory that should be backed up
export RMG_SERVER_ARCHIVE_DIR="$RMG_SERVER_DIR/archive"

# The location of the site configuration file sitelist.csv
# This file is used by server scripts to configure remote sites.
export RMG_SERVER_SITELIST="$RMG_SERVER_METADATA_DIR/sitelist.csv"

# The location on the server for det files from remote sites.
export RMG_SERVER_DET_DIR="$RMG_SERVER_DIR/det_files"

# The location on the server for processed det files
export RMG_SERVER_DET_ARCHIVE="$RMG_SERVER_ARCHIVE_DIR/det_files"

# The location on the server for estimator output files.
export RMG_SERVER_EST_DIR="$RMG_SERVER_DIR/est_files"

# The location on the server for est files that have been uploaded to the database.
export RMG_SERVER_EST_ARCHIVE="$RMG_SERVER_ARCHIVE_DIR/est_files"

# The maximum number of attempts to start the pulse detector before a
# fatal error state is reached. This value is needed by the site.
export RETRY_MAX=3

# Set the path used by gnuplot to find fonts used for the status plots
export GDFONTPATH=/usr/share/fonts/truetype/ttf-dejavu

# Set the name of the default font that gnuplot should use for the status plots
export GNUPLOT_DEFAULT_GDFONT=DejaVuSans

# Serial Port to communicate to the RMG receiver with
export RMG_SERIAL_PORT=/dev/ttyUSB0

# Time interval (in seconds) to look at frequency tunings
export RMG_TUNE_TIME=10

# Log directory for remotes
export RMG_SITE_LOG_DIR="$RMG_SITE_METADATA_DIR/log"

# Log directory for server
export RMG_SERVER_LOG_DIR="/var/log/rmg"

# Path for mount point of archive backup drive
export BACKUP_DRIVE=/mnt/external

# Path for mount point of archive backup drive2
export BACKUP_DRIVE2=/mnt/external2

# Path for rmg_server directory on archive backup drive
export BACKUP_DIR=$BACKUP_DRIVE/backup/$RMG_SERVER_DIR

# Path for rmg_server directory on archive backup drive2
export BACKUP_DIR2=$BACKUP_DRIVE2/backup/$RMG_SERVER_DIR

# Path for archive directory on backup drive
export BACKUP_ARCHIVE_DIR=$BACKUP_DIR/archive

#END

