#!/bin/bash
#rmg_det_to_est
#
# This script is part of the QRAAT system.
#
# Copyright (C) 2013 Todd Borrowman
#
# This script converts det files to est files and moves the det files
# to the det archive.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Check for attempted reentry
name=$(basename $0)
count=$(pgrep -c $name)
if [ "$count" -gt "1" ]
then
	echo $name already running, bye!
	exit 1
fi
#
echo Starting `date`

source rmg_env

SITES=$(ls -1 $RMG_SERVER_DET_DIR)

for SITE in $SITES
  do
    site_dir=$RMG_SERVER_DET_DIR/$SITE/
    leaf_dirs=$(find $site_dir -type d -links 2 | sort -r | head -20)
    for leaf_dir in $leaf_dirs
      do
        subdirectory=${leaf_dir#$site_dir}
        est_processing $leaf_dir $RMG_SERVER_EST_DIR/$SITE/$subdirectory
        mkdir -p $RMG_SERVER_DET_ARCHIVE/$SITE/$subdirectory
        mv $leaf_dir $RMG_SERVER_DET_ARCHIVE/$SITE/$subdirectory
    done
    find $site_dir -depth -empty -delete
done
echo Finished `date`
#END
