#!/bin/bash
#rmg_clean
#
# This script is part of the QRAAT system.
#
# Copyright (C) 2013 Marcel Losekoot
#
# This script is responsible for cleaning out the various directories that get archived.
# Call this script from cron:
#	59 15 * * * rmg_clean
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Check for attempted reentry
name=`basename $0`
count=`pgrep -c $name`
if [ "$count" -gt "1" ]
then
	echo $name already running, bye!
	exit 1
fi

echo
echo Starting $0 at `date`
# Set RMG environment variables
source rmg_env

# Find all expired files and check if they're backed up and then delete them.
badcount=0
rmcount=0
cd $RMG_SERVER_ARCHIVE_DIR
for filename in `find . -type f -mtime +$RMG_ARCHIVE_DAYS`
do
	destination=$BACKUP_ARCHIVE_DIR/$filename
	if [[ -e $destination ]]
	then
		let rmcount=$rmcount+1
		rm -f $filename
	else
		echo Missing from backup: $destination
		let badcount=$badcount+1
	fi
done

# Remove empty directories
#find . -type d -depth -empty -delete
find . -depth -type d -empty -delete

echo Found $badcount files that are not backed up
echo Found $rmcount files for deletion

echo Finished $0 at `date`

#END
