#!/usr/bin/python
# rmg_det_to_db
# Batch process det files into the datbase. This script is part of the 
# QRAAT system. 
#
# Copyright (C) 2013 Christopher Patton
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys, os, commands, errno
import re, time
import MySQLdb as mdb
import qraat 

# Check for running instances of this program. 
(status, output) = commands.getstatusoutput(
  'pgrep -c `basename %s`' % (sys.argv[0]))
if int(output) > 1: 
  print >>sys.stderr, "det_to_db: error: attempted reentry, exiting"
  sys.exit(1)

try: # Get some environment variables. 
  det_dir  = os.environ['RMG_SERVER_DET_DIR']
  det_arch = os.environ['RMG_SERVER_DET_ARCHIVE']
  est_arch = os.environ['RMG_SERVER_EST_ARCHIVE']
except KeyError: 
  print >>sys.stderr, "det_to_db: error: undefined environment variables. Try `source rmg_env.`"
  sys.exit(1)

try: # Get database credentials. 
  db_config = qraat.csv("%s/db_auth" % os.environ['RMG_SERVER_DIR']).get(view='writer')
except IOError, e: 
  print >>sys.stderr, "det_to_db: error: missing DB credential file '%s'." % e.filename
  sys.exit(1)
  


leaf_regex = re.compile("([0-9]{4})/([0-9]{2})/([0-9]{2})/([0-9]{2})/([0-9]{2})") 

try: 
  start = time.time()
  print "det_to_db: start time:", time.asctime(time.localtime(start))

  db_con = mdb.connect(db_config.host, 
                       db_config.user, 
                       db_config.password, 
                       db_config.name)

  cur = db_con.cursor()

  cur.execute('''SELECT name 
                   FROM sitelist''')

  for site in map(lambda row: row[0], cur.fetchall()):

    site_dir = '%s/%s' % (det_dir, site)
    
    # Don't process sites currently being fetched. 
    if not os.path.isfile('%s/fetching.site' % (site_dir)):
              
      (status, output) = commands.getstatusoutput(
        '/usr/bin/find %s/%s/????/??/??/??/?? -type d' % (
          det_dir, site))
           
      if status == 0:
    
        # Batch process only the newest 20 directories that were created.
        leaf_dirs = sorted(output.split('\n'), reverse=True)
        total = len(leaf_dirs) 
        leaf_dirs = leaf_dirs[:20]
        print "det_to_db: %s: processing %d out of %d available directories" % ( 
          site, len(leaf_dirs), total) 

        for leaf_dir in leaf_dirs:

          # Process det files, store signals in the databse. 
          table = qraat.est(dets=qraat.det.read_dir(leaf_dir))
          cur = db_con.cursor()
          for row in table: 
            try:
              table.write_db_row(cur, row, site)
            except qraat.ResolveIdError, e:
              print >>sys.stderr, "det_to_db: warning: skipping est corresponding to '%s'" % e.filename
          cur.execute('COMMIT')
                  
          # Archive table as est file. 
          m = leaf_regex.search(leaf_dir) 
          table.write(("%s/%s/" % (est_arch, site)) +\
                       ("%s/%s/%s/%s/%s/" % m.groups(0)))
          
          # Archive processed det files.
          arch_fn = ("%s/%s/" % (det_arch, site)) +\
                     ("%s/%s/%s/%s/%s/" % m.groups(0))
          try:
            os.makedirs(arch_fn)
          except OSError, e:            # Catch if directory exists;
            if e.errno != errno.EEXIST: # otherwise, throw exception.  
              raise e

          arch_fn += site + (".%s.%s.%s.%s.%s.tar" % m.groups(0))
          if os.path.isfile(arch_fn): 
            (status, output) = commands.getstatusoutput(
              '/bin/tar -rf %s -C %s .' % (arch_fn, leaf_dir))
          else: 
            (status, output) = commands.getstatusoutput(
              '/bin/tar -cf %s -C %s .' % (arch_fn, leaf_dir))

          # Delete processed det files. 
          # TODO prune empty directories? 
          if status != 0: 
            print >>sys.stderr, "det_to_db: error: archiving %s: %s" % (
              site, output)
          else:  
            commands.getstatusoutput('rm -fr %s' % leaf_dir)

except mdb.Error, e: 
  print >>sys.stderr, "det_to_db: error: [%d] %s" % (e.args[0], e.args[1])

finally: 
  print "det_to_db: finished in %.2f seconds." % (time.time() - start)
