#!/usr/bin/python
# sitelist
# Input a CSV formatted site list on STDIN, return an entry or 
# modify the file and output to STDOUT. This script is part of the 
# QRAAT system. 
#
# Copyright (C) 2013 Christopher Patton
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import sys

if len(sys.argv) < 4 or len(sys.argv) > 5:
  print >> sys.stderr, "usage: sitelist.py <site> <parameter> [<value>]" 
  sys.exit(1)

sys.argv.append(None)

(row, col, value) = sys.argv[1:4]

headers = sys.stdin.readline().strip().split(',')
header = { headers[i] : i for i in range(len(headers)) }

for line in sys.stdin.readlines(): 
  line = line.strip().split(',')
  try: 
    if value == None and line[header["name"]] == row: # Just get value
      print line[header[col]]
    elif value: 
      if line[header["name"]] == row:
        line[header[col]] = value
      print ','.join(line)
  except IndexError: 
    pass

