#!/usr/bin/python
# rmg_track_auto_auto
# 
# Copyright (C) 2014 Christopher Patton
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import qraat, qraat.srv
import time, os, sys, commands
import MySQLdb as mdb
from optparse import OptionParser

# Check for running instances of this program. 
(status, output) = commands.getstatusoutput(
  'pgrep -c `basename %s`' % (sys.argv[0]))
if int(output) > 1: 
  print >>sys.stderr, "track_auto: error: attempted reentry, exiting"
  sys.exit(1)

try: 
  start = time.time()
  print "track_auto: start time:", time.asctime(time.localtime(start))

  db_con = qraat.util.get_db('writer')

  # Get positionID of last processed position.  
  cur = db_con.cursor()
  cur.execute('SELECT value FROM qraat.cursor WHERE name=\'track_pos\'')
  last_processed = cur.fetchone()
  if last_processed is None: 
    last_processed = 0
    cur.execute('INSERT INTO qraat.cursor (name, value) VALUE (\'track_pos\', 0)')
  else: last_processed = int(last_processed[0])

  # Get a list of depIDs with new positions and their earliest timestamp. 
  cur.execute('''SELECT DISTINCT deploymentID 
                   FROM qraat.position 
                  WHERE ID > %s''', (last_processed))

  rows = map(lambda(row) : int(row[0]), cur.fetchall())
  print "track_auto: new data for", rows
 
  # Process new positions for each depID. 
  max_processed = last_processed
  for dep_id in rows:
    cur.execute('''SELECT min(timestamp), max(timestamp) 
                     FROM qraat.position 
                    WHERE deploymentID=%d
                      AND ID > %d''' % (dep_id, last_processed))
    
    (t_start, t_end) = map(lambda(t) : float(t), (cur.fetchone()))
    print "track_auto: deploymentID=%d, [%.2f, %.2f]" % (dep_id, t_start, t_end)
  
    print "track_auto: deploymentID=%d: fetching positions ..." % dep_id,
    pos_ids = qraat.srv.track.get_pos_ids(db_con, dep_id, t_start, t_end)
    pos = qraat.srv.position.Position(db_con, pos_ids)
    print len(pos)
  
    print "track_auto: deploymentID=%d: calculating ..." % dep_id,
    track = qraat.srv.track.calc_tracks(db_con, pos, dep_id, C=-5)
    print len(track)

    print "track_auto: deploymentID=%d: updating tracks." % dep_id
    track.insert_db(db_con)
    
    # New cursor is the maximum id processed during this run
    max_processed = max(max_processed, max(pos_ids))

  if max_processed > last_processed: 
    print "track_auto: updating cursor to positionID=%d." % max_processed
    cur.execute('''UPDATE qraat.cursor 
                      SET value=%d 
                    WHERE name="track_pos" ''' % max_processed)  
  

except mdb.Error, e:
  print >>sys.stderr, "track_auto: error: [%d] %s" % (e.args[0], e.args[1])
  sys.exit(1)

except qraat.error.QraatError, e:
  print >>sys.stderr, "track_auto: error: %s." % e

finally: 
  print "track_auto: finished in %.2f seconds." % (time.time() - start)
