#!/bin/bash
# rmg-node
# This script is part of the QRAAT system.
#
# Copyright (C) 2013 Christopher Patton
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

source rmg_env  # setup RMG environment variables

function help() {
  cat <<!EOF!
usage: rmg-node state/help [-options]

  This program is part of the QRAAT system. It controls the field site 
  by transitioning the computer to the specified state.  

  'state' is any one of the following:

    active       Computer is powered, RMG receiver is on, and the pulse 
                 detector is running. 

    up           Computer is powered, but RMG receiver is off and the 
                 pulse detector is stopped. 

    down [-d M]  RMG receiver is off, the pulse detector is stopped, and 
                 there is a timer set to shutdown. If such a timer exists
                 and delay is specified, it is reset to M minutes. If one 
                 doesn't exist, an M-minute timer is created (5 minutes 
                 if unspecified.)  

  'help' prints this help. 
!EOF!
}


## Get goal state and options ##
GOAL=$1 

if [ ! $GOAL ]
then
  help 
  exit 0 
fi

case $GOAL in
 -h|--help|help)
   help
   exit 0
  ;; 
  
  up|active)
  ;; 

  down)
    shift
    if [[ "$1" == "-d" ]] || [[ "$1" == "--delay" ]] 
    then
      DELAY=$2
      DELAY_SPECIFIED=1
    else     
      DELAY=5
    fi
  ;;
  
  *)
    echo error: unrecognized state \'$GOAL\'
    exit 1
  ;;

esac 


## Site configuration ##
SITE=$RMG_SITE_METADATA_DIR/site.csv
STATUS_LOG=$RMG_SITE_METADATA_DIR/status.log
if [ ! -e $SITE ]
then
  echo "error: site configuration information not available (no site.csv)." 1>&2
  exit 1
fi 

if [ ! -e $STATUS_LOG ]
then
  echo "timestamp,site_status" | cat >> $STATUS_LOG
fi

if [ ! $RETRY_CT ] || [ ! $RETRY_MAX ]
then
  echo "warning: setting retry count to zero." 1>&2
  RETRY_CT=0
  RETRY_MAX=10
fi 


## Collect status information ##
TYPE=$(rmg_sitelist --column powertype <$SITE)
IP=$(rmg_sitelist --column power_ip <$SITE)
RX_OUTLET=$(rmg_sitelist --column rx_outlet <$SITE)

RX_STATE=$(rmg_powerswitch $TYPE $IP $RX_OUTLET QUERY)
SDR_PID=$(pgrep run_rmg)

PREV_STATUS=$(rmg_sitelist --column site_status <$STATUS_LOG | tail -1)
PREV_TIME=$(rmg_sitelist --column timestamp <$STATUS_LOG | tail -1)


## Transition functions ##
function up() {
  if [ $RX_STATE -eq 0 ] && [ ! $SDR_PID ]
    then
      echo up
  else
      if [ $RX_STATE -ne 0 ]                   # RMG receiver off
        then rmg_powerswitch $TYPE $IP $RX_OUTLET OFF; fi 
      if [ $SDR_PID ]                          # Pulse detector stopped
        then kill -s INT $SDR_PID; fi
      echo up
  fi
}

function down() {
  if [ $RX_STATE -eq 0 ] && [ ! $SDR_PID ] 
    then 
      echo down\($(($DELAY * 60))\)
  else 
      if [ $RX_STATE -ne 0 ]                   # RMG receiver off
        then rmg_powerswitch $TYPE $IP $RX_OUTLET OFF; fi 
      if [ $SDR_PID ]                          # Pulse detector stopped
        then kill -s INT $SDR_PID; fi
      echo down\($(($DELAY * 60))\)
  fi
}

function active() {
  if [ $RETRY_CT -gt $RETRY_MAX ]
    then 
      if [ $RX_STATE -ne 0 ]                   # RMG receiver off
       then rmg_powerswitch $TYPE $IP $RX_OUTLET OFF; fi 
      if [ $SDR_PID ]                          # Pulse detector stopped
        then kill -s INT $SDR_PID; fi
      echo err_fatal
   
  elif [ $RX_STATE -eq 1 ] && [ $SDR_PID ]
    then
      let RETRY_CT=0
      echo active
  
  else 
      if [ $RX_STATE -ne 1 ]                   # RMG receiver on
       then rmg_powerswitch $TYPE $IP $RX_OUTLET ON; fi 
      if [ ! $SDR_PID ]                        # Pulse detector running
        then 
          run_rmg -d $RMG_SITE_DET_DIR \
                  -f $RMG_SITE_METADATA_DIR/tx.csv \
                  -p /dev/ttyUSB0 \
                  1> $RMG_SITE_METADATA_DIR/run_rmg$(date -d 'today' +'%Y.%m.%d_%H.%M').txt \
                  2> $RMG_SITE_METADATA_DIR/run_rmg_error.txt &
      fi
      let RETRY_CT=RETRY_CT+1
      echo err_retry\($RETRY_CT\)
  fi
}


## Execute state transition ##
case $GOAL in
  active)
    STATUS=`active`
  ;; 

  up)
    STATUS=`up`
  ;; 

  down)
    STATUS=`down`
  ;;
  
esac 


## Log new state, shutdown if time has elapsed ## 
TIME=`date -u +%s`
case $STATUS in
  
  down\(*\))

    # If no delay is specied and the previous status was down, we 
    # need to check if the delay specified by the last status has 
    # elapsed. If so, log the shutdown and power off the system. 
    # If a delay is specified, we need to reset the timer. If a the 
    # previous status was not down, then we need to set a new timer. 

    ## Check if it's time to go down ##
    D=$(echo $PREV_STATUS | grep down | grep -o -e "[0-9]*")
    if [ ! $DELAY_SPECIFIED ] && [ $D ] && [ $PREV_TIME ] && [ $(($TIME - $PREV_TIME)) -gt $D ]
      then
        echo "$TIME,shutdown" | cat >> $STATUS_LOG
        echo "time to shutdown!" # TODO

    ## reset timer or set a new one ##
    elif [ $DELAY_SPECIFIED ] || [ ! $D ]
      then
        echo "$TIME,$STATUS" | cat >> $STATUS_LOG
    fi
  ;;

  active|up|shutdown|err_*)

    # All other transitions are handled the same way. 

    if [[ "$STATUS" != "$PREV_STATUS" ]]
      then echo "$TIME,$STATUS" | cat >> $STATUS_LOG
    fi
  ;;

esac

