#!/bin/bash
# rmg_env
#
# This script is part of the QRAAT system. It provides system variables
# for running QRAAT.
#
# NB: Each variable must be defined using the export command.
#
# Copyright (C) 2013 Todd Borrowman
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


#Server directory and file locations

# The directory on the server where the server RMG files are stored.
# This convenience variable is local to this script.
export RMG_SERVER_DIR="/rmg_server"

# Location of metadata on the server. Files included in this directory
# are sitelist.csv and transmitter spec files.
export RMG_SERVER_METADATA_DIR="$RMG_SERVER_DIR"

# Location of archive on the server, used to store processed det and est files
# This vairable is used to identify the directory that should be backed up
export RMG_SERVER_ARCHIVE_DIR="$RMG_SERVER_DIR/archive"

# The location of the site configuration file sitelist.csv
# This file is used by server scripts to configure remote sites.
export RMG_SERVER_SITELIST="$RMG_SERVER_METADATA_DIR/sitelist.csv"

# The location of the transmitter configuration file tx.csv
# This file is used by server scripts to configure remote sites.
export RMG_SERVER_TXLIST="$RMG_SERVER_METADATA_DIR/tx.csv"

# The location of the database authentication file
# This file is used by server scripts to access the database.
export RMG_SERVER_DB_AUTH="$RMG_SERVER_METADATA_DIR/db_auth"

# Keys related to web-based user interface. The Django 
# project 'qraatview' expects values for 'google_maps_js_api' 
# and 'django_base'. 
export RMG_SERVER_UI_KEYS="$RMG_SERVER_METADATA_DIR/ui_keys"

# The location on the server for det files from remote sites.
export RMG_SERVER_DET_DIR="$RMG_SERVER_DIR/det_files"

# The location on the server for processed det files
export RMG_SERVER_DET_ARCHIVE="$RMG_SERVER_ARCHIVE_DIR/det_files"

# The location on the server for estimator output files.
export RMG_SERVER_EST_DIR="$RMG_SERVER_DIR/est_files"

# The location on the server for est files that have been uploaded to the database.
export RMG_SERVER_EST_ARCHIVE="$RMG_SERVER_ARCHIVE_DIR/est_files"

# Log directory for server
export RMG_SERVER_LOG_DIR="/var/log/rmg"

#END#Server directory and file locations


#Backup system files and parameters

# Path for mount point of backup drive
# Used in rmg_backup
# Comment this out to disable backups (e.g. when drive is not mounted)
export RMG_BACKUP_DRIVE=/mnt/external

# Paths for subdirectories of rmg_server directory on backup drive
if [ ! -z "${RMG_BACKUP_DRIVE}" ]
then
	export RMG_BACKUP_DIR=${RMG_BACKUP_DRIVE}/backup${RMG_SERVER_DIR}
	export RMG_BACKUP_ARCHIVE_DIR=$RMG_BACKUP_DIR/archive
fi

# Path for mount point of secondary backup drive2
# Used in rmg_backup
# Comment this out to disable secondary backups (e.g. when drive is not mounted)
export RMG_BACKUP_DRIVE2=/mnt/external2

# Paths for subdirectories of rmg_server directory on secondary backup drive
if [ ! -z "${RMG_BACKUP_DRIVE2}" ]
then
	export RMG_BACKUP_DIR2=${RMG_BACKUP_DRIVE2}/backup${RMG_SERVER_DIR}
fi

# Path to backup directory on the frontend virtual machine
export RMG_BACKUP_FRONTEND=qraat-frontend:/mnt/backup/backup/rmg_server

# The number of days that files stay in RMG_SERVER_ARCHIVE_DIR
# Used in rmg_clean
export RMG_ARCHIVE_DAYS=3

#END#Backup system files and parameters


#RMG receiver operation parameters

# Location of metadata on a remote machine. Files included in this
# directory are: site.csv, tx.csv, and status.log. Any debug information
# is also stored here. We currently log the standard output and standard
# error of the last run of the pulse detector. This value is used by the
# server and must be the same at each site.
export RMG_SITE_METADATA_DIR="/home/rmg"

# Location of det data files on a remote machine. This is typically a
# subdirectory of a temporary filesystem created with /etc/fstab.
# This value is used by the sever and must be the same at each site.
export RMG_SITE_DET_DIR="/tmp/ramdisk/det_files"

# Log directory for remotes
export RMG_SITE_LOG_DIR="$RMG_SITE_METADATA_DIR/log"

# The maximum number of attempts to start the pulse detector before a
# fatal error state is reached. This value is needed by the site.
export RETRY_MAX=3

# Serial Port to communicate to the RMG receiver with
export RMG_SERIAL_PORT=/dev/ttyUSB0

# Time interval (in seconds) to look at frequency tunings
export RMG_TUNE_TIME=10

#END#RMG receiver operation parameters


#Status plotting parameters

# Set the path used by gnuplot to find fonts used for the status plots
export GDFONTPATH=/usr/share/fonts/truetype/ttf-dejavu

# Set the name of the default font that gnuplot should use for the status plots
export GNUPLOT_DEFAULT_GDFONT=DejaVuSans

#END#Status plotting parameters


#Processing parameters

#det_to_db

# Quarantine directory for bad files
export RMG_QUARANTINE_DIR=$RMG_SERVER_DIR/quarantine

# Quarantine directory for bad det files
export RMG_SERVER_DET_QUARANTINE=$RMG_QUARANTINE_DIR/det_files

# Max number of minute-directories per site to process at a time
export RMG_DIRECTORY_THROTTLE=20

#END#det_to_db

#filter_auto

# Max number of est records to be processed at a time (not a hard limit, see documentation)
export RMG_EST_THROTTLE=50000

# Time window to estimate the pulse interval
export RMG_EST_SCORE_INTERVAL=60

# Time window to score est records for corroborators
export RMG_EST_SCORE_NEIGHBORHOOD=20

#END#filter_auto

#position_auto

# Averaging window used for auto position calculation
export RMG_POS_TIME_WINDOW=15

# Time step for auto position calculation
export RMG_POS_TIME_STEP=15

# Calibration data to use in auto position calculation
export RMG_POS_CAL_ID=3

# EST Score Threshold for filter before position estimation
export RMG_POS_EST_THRESHOLD=0.0

# Enable covariance estimation 
export RMG_POS_ENABLE_COV=true

# Normalize beaaring spectrum
export RMG_POS_NORMALIZE_SPECTRUM=false

#END#position_auto

#track_auto

#END#track_auto

#END#Processing parameters


#transmitter default parameters

# RMG pulse detector default rise theshold trigger
export RMG_PULSE_RISE=1.5

# RMG pulse detector default time constant
export RMG_PULSE_TIME_CONSTANT=10.0

#END#transmitter default parameters

#END

