#!/usr/bin/env python2

import time, sys, datetime

try: 
  print time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(float(sys.argv[1])))

except ValueError: 
  print time.mktime(datetime.datetime.strptime(sys.argv[1], '%Y-%m-%d %H:%M:%S').timetuple())
