#!/usr/bin/python 
# run_pulse.py
# display contents of a .det file
# Christopher Patton Dec 2011 / Aug 2012

from gnuradio import gr, blks2, uhd, gru
import rmg, sys

if(len(sys.argv) == 1):
  print "usage: read_det pulse_data.det"
  sys.exit(1)

det = rmg.pulse_data(sys.argv[1])
p = det.param()


print p

print ' '*4,
for i in range(p.channel_ct-1): 
  print "%-21s  |" % ('channel %d' % (i+1)),
print 'channel %d' % p.channel_ct
print '-'*4 + ('-'*24+'+')*(p.channel_ct-1) + '-'*22

for i in range(p.data_ct):
  print "%-4d" % (i+1) + "    |".join(
   [ "%-4f  %-4f" % (det.real((i*p.channel_ct)+j), 
                     det.imag((i*p.channel_ct)+j))
      for j in range(p.channel_ct) ] ) 
    
