#!/usr/bin/python 
# read_det 
# Display the contents of .det files. This file is part of QRAAT, an 
# automated animal tracking system based on GNU Radio. 
#
# Copyright (C) 2012 Christopher Patton
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from gnuradio import gr, blks2, uhd, gru
import qraat.rmg, sys

if(len(sys.argv) == 1):
  print "usage: read_det pulse_data.det"
  sys.exit(1)

det = rmg.detection.pulse_data(sys.argv[1])
p = det.param()


print p

print ' '*4,
for i in range(p.channel_ct-1): 
  print "%-21s  |" % ('channel %d' % (i+1)),
print 'channel %d' % p.channel_ct
print '-'*4 + ('-'*24+'+')*(p.channel_ct-1) + '-'*22

for i in range(p.data_ct):
  print "%-4d" % (i+1) + "    |".join(
   [ "%-4f  %-4f" % (det.real((i*p.channel_ct)+j), 
                     det.imag((i*p.channel_ct)+j))
      for j in range(p.channel_ct) ] ) 
    
