<html>
<head>
<title>QRAAT Status</title>
<meta http-equiv=\"refresh\" content=\"60\">
<meta http-equiv="cache-control" content="no-cache">
<style type="text/css">
table.status {
	font-family: verdana,arial,sans-serif;
	font-size:11px;
	color:#333333;
	border-width: 1px;
	border-color: #666666;
	border-collapse: collapse;
}
table.status th {
	border-width: 1px;
	padding: 8px;
	border-style: solid;
	border-color: #666666;
	background-color: #dedede;
}
table.status td {
	border-width: 1px;
	padding: 8px;
	border-style: solid;
	border-color: #666666;
	background-color: #ffffff;
}
</style>
</head>
<body>
<h1>System Status</h1>
<p><a href="telemetry.html">Site telemetry</a></p>
<p><a href="processing.html">Processing</a></p>
<p><a href="frequency.html">Frequency</a></p>
<p><a href="power.html">Power</a></p>
<p><a href="showfest.php">Activity</a></p>
<?php
	$df = disk_free_space("/") ;
	$dt = disk_total_space("/") ;
	$pc = intval(100*$df/$dt) ;
	$fc = "#000000" ;
	if( $pc < 10 )
	{
		$fc = "#FF0000" ;
	}
	print "<p><font color=\"$fc\">Free disk space on / is $pc%</font></p>\n" ;
	include("qr_status.php") ;
	qr_status() ;
?>
</body>
</html>
